options:
  cluster-name:
    type: string
    default: "elasticsearch"
    description: |
      This sets the elasticsearch cluster name.
  firewall_enabled:
    type: boolean
    default: true
    description: |
      By default, the admin and peer ports (9200 and 9300) are only accessible
      to clients and peers respectively. Switch this to false to enable access
      from any machine.
